---
abstract: 'create elevation graphs from GPX files'
author:
  - 'Markus Benning <me@w3r3wolf.de>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300020, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: GPX-PlotElevation
requires:
  Chart::Gnuplot: 0
  Geo::Distance: 0
  Geo::Gpx: 0
  Getopt::Long: 0
  IO::File: 0
  POSIX: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=GPX-PlotElevation
  repository: https://github.com/benningm/GPX-PlotElevation
version: 1.01
